### ISSUE TITLE
create send2cgeo icon in the new design

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo.github.io#235]
Currently I found 
https://send2.cgeo.org/content/images/send2cgeo.png
https://send2.cgeo.org/send2cgeo.png
but not in a place of version control.
This icons should have the new design.
@pstorch Can you create this?

**Comment by pstorch** [comment]
It's coming from an iframe:
![image](https://user-images.githubusercontent.com/5598124/88584416-e0c29b80-d051-11ea-9e68-c2ee2ed70c95.png)

Does someone know where the sources of the images are? Not in this repo.

**Comment by Lineflyer** [comment]
At least there is some version in the c:geo repo as we use it in useful apps...else, no idea.

**Comment by moving-bits** [comment]
> At least there is some version in the c:geo repo as we use it in useful apps...else, no idea.

That would be `res/drawable-hdpi/cgeo_sendto.png`

**Comment by pstorch** [comment]
I'm looking for the SVGs, the others where here: https://github.com/cgeo/cgeo/tree/master/main/project/rawimages

**Comment by pstorch** [comment]
A first experiment:

![image](https://user-images.githubusercontent.com/5598124/89512426-80f78d80-d7d3-11ea-80ec-4c06e7ada2ff.png)

The  Sphere as the target of the arrow is too much I think, that's why I've omitted it. 
As the background is now mainly orange, I changed the colour of the arrow to the same green gradient as the c:geo box.
I still have some doubts about the drop shadows. The original image had 3 different kinds of shadows. I could change it to a blurred drop shadow, but then it is different to the c:geo launcher icon.

What do you think?

**Comment by Lineflyer** [comment]
It looks not so nice IMHO.

How about a "send2" text within the arrow?
