### ISSUE TITLE
Shortend anchors for FAQ might be to short

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo.github.io#63]
Example:
http://cgeo.github.io/faq.html#faq.Iamnotable

There are two entries matching it.

I could try to manually avoid it by changing the title, still this is no failsafe method.
Suggestions?

**Comment by Bananeweizen** [comment]
Actually I'm thinking that removing the auto-generated anchor might be the best solution. I.e. just add another data item for each faq entry, like 
```
title: I am new to Geocaching. How does all of this work?
anchor: newbie
content: |
            Explaining all details of Geocaching ...
```

Then we can simply use 
```
{{item.anchor}}
```
in the faq.html instead of the automatically shortened title.

This has multiple benefits:
* anchors become more readable (which you will surely notice when posting them on facebook)
* anchors don't change when someone updates a FAQ title, which otherwise breaks cross links

If we change this, then I suggest to also remove the "faq." part in the anchor, as it appears twice in the URL and doesn't add any value.

Note: I've not tested anything of my suggestions, as I didn't get jekyll running yet.

**Comment by SammysHP** [comment]
https://github.com/cgeo/cgeo.github.io/issues/15#issuecomment-73488053
https://github.com/cgeo/cgeo.github.io/issues/15#issuecomment-74905557

You can add the anchor key (for all faq entries) and I'll make the necessary modifications to our script.

**Comment by Lineflyer** [comment]
> You can add the anchor key (for all faq entries) and I'll make the necessary modifications to our script.

Who are you adressing?

**Comment by SammysHP** [comment]
@Lineflyer You, it's your FAQ. ;)

**Comment by Lineflyer** [comment]
@SammysHP Can you do an example for me so that I understand the way it will work? Then I can do the rest of the work for sure.

**Comment by SammysHP** [comment]
```yaml

      - title: This is the title
        id: this-is-the-title
        content: |
            This is the content…
```
